docs/blockchain/executor-agent.rst, docs/blockchain/executor-wallet.rst, docs/blockchain/wallet.rst, docs/contracts/data-contract.rst, docs/contracts/rights-and-roles.rst, docs/contracts/sharing.rst, docs/dfs/ipld.rst, docs/profile/business-center-profile.rst, docs/profile/mailbox.rst
- [CORE-312]
[CORE-312]: https://evannetwork.atlassian.net/browse/CORE-312
=> fix broken links

docs/profile/verifications.rst
- [CORE-526]
[CORE-526]: https://evannetwork.atlassian.net/browse/CORE-526
=> add verfication data example

src/contracts/digital-twin/container.spec.ts, src/contracts/digital-twin/container.ts
- [CORE-598]
[CORE-598]: https://evannetwork.atlassian.net/browse/CORE-598
=> fix creating multiple containers at the same time

src/onboarding.ts, src/profile/types/user.ts
- [CORE-604]
[CORE-604]: https://evannetwork.atlassian.net/browse/CORE-604
=> prefill missing profile type

src/contracts/sharing.ts
- [CORE-642]
[CORE-642]: https://evannetwork.atlassian.net/browse/CORE-642
=> fix value handling in sharing

src/contracts/digital-twin/container.spec.ts
- [CORE-639]
[CORE-639]: https://evannetwork.atlassian.net/browse/CORE-639
=> test 5 parallel containers

VERSIONS.md, docs/contracts/container.rst, docs/contracts/rights-and-roles.rst, docs/profile/verification-usage-examples.rst, src/contracts/digital-twin/container.spec.ts, src/contracts/digital-twin/container.ts, src/contracts/digital-twin/digital-twin.spec.ts
- replace older occurrences of "validations" with "verifications"
- [CORE-698]
[CORE-698]: https://evannetwork.atlassian.net/browse/CORE-698
=> update naming of verifications

src/runtime.spec.ts, src/runtime.ts
-[CORE-485]
[CORE-485]: https://evannetwork.atlassian.net/browse/CORE-485
=> added check for invalid account map and respective test

VERSIONS.md, docs/profile/did-resolver.rst, src/did/did-resolver.spec.ts, src/did/did-resolver.ts
- [CORE-729]
[CORE-729]: https://evannetwork.atlassian.net/browse/CORE-729
=> add `getService`, `setService` to `DidResolver`

.github/workflows/lint.yml, .travis.yml, package.json, src/contracts/digital-twin/digital-twin.spec.ts
- [CORE-748]
[CORE-748]: https://evannetwork.atlassian.net/browse/CORE-748
=> add linting action

.eslintignore, .gitignore, .npmignore, package.json, tsconfig-test.json
- [CORE-748]
[CORE-748]: https://evannetwork.atlassian.net/browse/CORE-748
=> update pre-commit build to include spec files

README.md, VERSIONS.md
- [CORE-512]
[CORE-512]: https://evannetwork.atlassian.net/browse/CORE-512
=> change links for browserified version to ui-dapps

VERSIONS.md
- [CORE-847]
[CORE-847]: https://evannetwork.atlassian.net/browse/CORE-847
=> update version info

src/dfs/ipfs.ts, src/dfs/ipld.ts
- [CORE-816]
[CORE-816]: https://evannetwork.atlassian.net/browse/CORE-816
=> fix ipfs timers

VERSIONS.md, package.json, src/contracts/digital-twin/container.spec.ts, src/contracts/digital-twin/container.ts, src/contracts/digital-twin/digital-twin.spec.ts, src/contracts/digital-twin/digital-twin.ts
- [CORE-690]
[CORE-690]: https://evannetwork.atlassian.net/browse/CORE-690
=> dbcpVersion 2 and empty containerConfig

VERSIONS.md, src/config-core.ts, src/config-testcore.ts, src/verifications/verifications.spec.ts, src/verifications/verifications.ts
- [CORE-799]
[CORE-799]: https://evannetwork.atlassian.net/browse/CORE-799
=> update root verification handling to use genesis account

docs/contracts/digital-twin-usage-examples.rst, docs/contracts/digital-twin.rst
- [CORE-898]
[CORE-898]: https://evannetwork.atlassian.net/browse/CORE-898
=> use external twin sample for documentation

VERSIONS.md, src/contracts/data-contract/data-contract.spec.ts, src/contracts/data-contract/data-contract.ts
- [CORE-880]
[CORE-880]: https://evannetwork.atlassian.net/browse/CORE-880
=> fix behavior of `DataContract` for unencrypted data

src/onboarding.ts
=> fix onboarding with identity

src/onboarding.ts
=> fix onboarding with identity v2

VERSIONS.md, src/contracts/digital-twin/digital-twin.spec.ts, src/contracts/digital-twin/digital-twin.ts
- [CORE-944]
[CORE-944]: https://evannetwork.atlassian.net/browse/CORE-944
=> fix digital template plugins are not checked for valid ajv schema

VERSIONS.md, docs/profile/did.rst, src/did/did.spec.ts, src/did/did.ts
=> add support for custom DID registries for DID tests

src/onboarding.ts, src/runtime.ts
=> fix internal signer when creating offline profile

.eslintrc.js, VERSIONS.md, package.json, src/contracts/digital-twin/container.ts, src/contracts/digital-twin/digital-twin.ts, src/contracts/wallet.ts, src/dfs/ipfs.ts, src/dfs/ipld.ts, src/did/did.ts, src/encryption/aes-blob.ts, src/keyExchange.ts, src/onboarding.ts, src/profile/profile.ts, src/verifications/verifications.ts
=> add `member-ordering` rule and update code

src/contracts/digital-twin/digital-twin.ts
- [CORE-939]
[CORE-939]: https://evannetwork.atlassian.net/browse/CORE-939
=> fix error for accounts without DID

src/did/did.spec.ts, src/did/did.ts, src/vc/vc.ts
[CORE-1004]
[CORE-1004]: https://evannetwork.atlassian.net/browse/CORE-1004
=> Removed case change when converting identities to dids

.travis.yml, docs/dfs/ipfs.rst, src/contracts/data-contract/data-contract.ts, src/dfs/ipfs.spec.ts, src/dfs/ipfs.ts
[CORE-775](https://evannetwork.atlassian.net/browse/CORE-775)
=> Updated ipfs.get method to match interface and improved test

VERSIONS.md, docs/profile/did.rst, src/contracts/digital-twin/digital-twin.ts, src/did/did.spec.ts, src/did/did.ts, src/vc/vc.ts
=> Refactoring

VERSIONS.md, src/did/did.spec.ts, src/did/did.ts
[CORE-1090]
[CORE-1090]: https://evannetwork.atlassian.net/browse/CORE-1090
=> Fixed default did document ethereum address to be lowercase & proofing bug

docs/contracts/digital-twin-usage-examples.rst
=> add default value documentation for twin templates

src/test/test-utils.ts
- [CORE-954]
[CORE-954]: https://evannetwork.atlassian.net/browse/CORE-954
=> fix executor-wallet tests

VERSIONS.md, docs/common/utils.rst, src/common/utils.ts
- [CORE-954]
[CORE-954]: https://evannetwork.atlassian.net/browse/CORE-954
=> send EvanIdentity as header by generating the evan auth message

VERSIONS.md, src/onboarding.ts
- [CORE-1314]
[CORE-1314]: https://evannetwork.atlassian.net/browse/CORE-1314
=> fix profile creation
